#include "Platform/VulkanDemo.h"
#include "Renderer/RHI/RHIDevice.h"
#include "Renderer/RHI/RHICommandList.h"
#include "Renderer/MeshData.h"

// Vulkan expects clip-space depth in [0, 1] (OpenGL uses [-1, 1]); make GLM's
// perspective matrix match before any glm header is pulled in.
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <spdlog/spdlog.h>

#include <array>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <vector>

namespace Diamond {

namespace {

// Matches mesh.vert's vertex inputs — a repacked subset of the engine's full
// MeshData::Vertex (position + normal + UV; skinning/tangents unused at M3).
struct MeshVertex {
    glm::vec3 pos;
    glm::vec3 normal;
    glm::vec2 uv;
};

// std140 per-frame UBO — mirrors FrameUBO in the shaders.
struct FrameUBO {
    glm::mat4 viewProj;
    glm::vec4 lightDir;
    float     time;
};

// Per-draw push constant — mirrors Push in mesh.vert.
struct PushConstants {
    glm::mat4 model;
};

std::vector<uint32_t> ReadSpirv(const std::string& path) {
    std::ifstream file(path, std::ios::binary | std::ios::ate);
    if (!file) {
        spdlog::critical("[RHI] failed to open SPIR-V '{}'", path);
        std::abort();
    }
    const std::streamsize bytes = file.tellg();
    std::vector<uint32_t> words(static_cast<size_t>(bytes) / sizeof(uint32_t));
    file.seekg(0);
    file.read(reinterpret_cast<char*>(words.data()), bytes);
    return words;
}

// A 256×256 RGBA8 checkerboard, generated CPU-side so the demo has no external
// asset dependency. Cells are large enough that linear filtering still reads
// clearly as a texture rather than a blur.
std::vector<uint8_t> MakeCheckerboard(uint32_t size, uint32_t cell) {
    std::vector<uint8_t> pixels(static_cast<size_t>(size) * size * 4);
    for (uint32_t y = 0; y < size; ++y) {
        for (uint32_t x = 0; x < size; ++x) {
            const bool even = ((x / cell) + (y / cell)) % 2 == 0;
            uint8_t* p = &pixels[(static_cast<size_t>(y) * size + x) * 4];
            p[0] = even ? 230 : 40;
            p[1] = even ? 180 : 60;
            p[2] = even ? 70  : 90;
            p[3] = 255;
        }
    }
    return pixels;
}

void OnFramebufferResize(GLFWwindow* window, int /*w*/, int /*h*/) {
    auto* device = static_cast<RHIDevice*>(glfwGetWindowUserPointer(window));
    if (device) device->NotifyResize();
}

} // namespace

int RunVulkanMeshDemo() {
    if (!glfwInit()) {
        spdlog::critical("[RHI] glfwInit failed");
        return 1;
    }
    if (!glfwVulkanSupported()) {
        spdlog::critical("[RHI] GLFW reports no Vulkan loader present");
        glfwTerminate();
        return 1;
    }

    glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);   // Vulkan window
    GLFWwindow* window = glfwCreateWindow(1280, 720, "DiamondEngine — Vulkan RHI Mesh", nullptr, nullptr);
    if (!window) {
        spdlog::critical("[RHI] glfwCreateWindow failed");
        glfwTerminate();
        return 1;
    }

    // Everything below this line is backend-neutral RHI pass code: swapping the
    // backend enum is all that picks Vulkan vs (eventually) another backend.
    std::unique_ptr<RHIDevice> device = RHIDevice::Create(window, RHIBackend::Vulkan);
    if (!device) {
        spdlog::critical("[RHI] device creation failed");
        glfwDestroyWindow(window);
        glfwTerminate();
        return 1;
    }

    glfwSetWindowUserPointer(window, device.get());
    glfwSetFramebufferSizeCallback(window, OnFramebufferResize);

    // Real geometry: a unit cube generated by the engine's mesh factory, repacked
    // into the demo's lean vertex layout.
    const MeshData cube = MeshData::UnitCube();
    std::vector<MeshVertex> vertices;
    vertices.reserve(cube.Vertices.size());
    for (const Vertex& v : cube.Vertices)
        vertices.push_back({ v.Position, v.Normal, v.TexCoords });
    const std::vector<uint32_t>& indices = cube.Indices;

    RHIBufferDesc vbDesc;
    vbDesc.size        = vertices.size() * sizeof(MeshVertex);
    vbDesc.usage       = RHIBufferUsage::Vertex;
    vbDesc.initialData = vertices.data();
    auto vertexBuffer = device->CreateBuffer(vbDesc);

    RHIBufferDesc ibDesc;
    ibDesc.size        = indices.size() * sizeof(uint32_t);
    ibDesc.usage       = RHIBufferUsage::Index;
    ibDesc.initialData = indices.data();
    auto indexBuffer = device->CreateBuffer(ibDesc);
    const uint32_t indexCount = static_cast<uint32_t>(indices.size());

    // Checkerboard texture (uploaded once through the staging path).
    const uint32_t kTexSize = 256;
    const std::vector<uint8_t> texPixels = MakeCheckerboard(kTexSize, 32);
    RHITextureDesc texDesc;
    texDesc.width       = kTexSize;
    texDesc.height      = kTexSize;
    texDesc.format      = RHIFormat::RGBA8;
    texDesc.initialData = texPixels.data();
    auto texture = device->CreateTexture(texDesc);

    // Per-frame UBO (dynamic — rewritten every frame).
    RHIBufferDesc uboDesc;
    uboDesc.size    = sizeof(FrameUBO);
    uboDesc.usage   = RHIBufferUsage::Uniform;
    uboDesc.dynamic = true;
    auto uniformBuffer = device->CreateBuffer(uboDesc);

    // Shaders.
    const std::string shaderDir = DIAMOND_VULKAN_SHADER_DIR;
    const std::vector<uint32_t> vertSpv = ReadSpirv(shaderDir + "/mesh.vert.spv");
    const std::vector<uint32_t> fragSpv = ReadSpirv(shaderDir + "/mesh.frag.spv");

    RHIShaderDesc vsDesc{ RHIShaderStage::Vertex,   vertSpv.data(), vertSpv.size() };
    RHIShaderDesc fsDesc{ RHIShaderStage::Fragment, fragSpv.data(), fragSpv.size() };
    auto vertexShader   = device->CreateShader(vsDesc);
    auto fragmentShader = device->CreateShader(fsDesc);

    // Pipeline (depth-tested; cube faces resolve by depth so culling stays off).
    RHIPipelineDesc pipeDesc;
    pipeDesc.vertexShader   = vertexShader.get();
    pipeDesc.fragmentShader = fragmentShader.get();
    pipeDesc.vertexLayout.stride = sizeof(MeshVertex);
    pipeDesc.vertexLayout.attributes = {
        { 0, RHIVertexFormat::Float3, offsetof(MeshVertex, pos)    },
        { 1, RHIVertexFormat::Float3, offsetof(MeshVertex, normal) },
        { 2, RHIVertexFormat::Float2, offsetof(MeshVertex, uv)     },
    };
    pipeDesc.resourceBindings = {
        { 0, RHIResourceType::UniformBuffer,        RHIShaderStage::Vertex | RHIShaderStage::Fragment },
        { 1, RHIResourceType::CombinedImageSampler, RHIShaderStage::Fragment },
    };
    pipeDesc.pushConstants = { RHIShaderStage::Vertex, sizeof(PushConstants) };
    pipeDesc.colorFormat   = device->SwapchainFormat();
    pipeDesc.depthFormat   = device->DepthFormat();
    pipeDesc.depthTest     = true;
    pipeDesc.depthWrite    = true;
    auto pipeline = device->CreatePipeline(pipeDesc);

    auto resourceSet = device->CreateResourceSet(
        pipeline.get(), 0, { { 0, uniformBuffer.get() } }, { { 1, texture.get() } });

    const std::array<float, 4> clear = { 0.02f, 0.02f, 0.05f, 1.0f };

    while (!glfwWindowShouldClose(window)) {
        glfwPollEvents();

        RHICommandList* cmd = device->BeginFrame(clear);
        if (!cmd) continue;   // frame skipped (minimized / swapchain rebuilt)

        const float t = static_cast<float>(glfwGetTime());

        int fbW = 0, fbH = 0;
        glfwGetFramebufferSize(window, &fbW, &fbH);
        const float aspect = fbH > 0 ? static_cast<float>(fbW) / fbH : 1.0f;

        // Orbiting camera framing the origin.
        const glm::vec3 eye = glm::vec3(std::sin(t) * 4.0f, 2.5f, std::cos(t) * 4.0f);
        const glm::mat4 view = glm::lookAt(eye, glm::vec3(0.0f), glm::vec3(0.0f, 1.0f, 0.0f));
        const glm::mat4 proj = glm::perspective(glm::radians(55.0f), aspect, 0.1f, 100.0f);

        FrameUBO ubo{};
        ubo.viewProj = proj * view;
        ubo.lightDir = glm::vec4(glm::normalize(glm::vec3(-0.4f, -1.0f, -0.3f)), 0.0f);
        ubo.time     = t;
        uniformBuffer->Update(&ubo, sizeof(ubo));

        PushConstants push{};
        push.model = glm::rotate(glm::mat4(1.0f), t * 0.5f, glm::vec3(0.0f, 1.0f, 0.0f));

        cmd->BindPipeline(pipeline.get());
        cmd->BindResourceSet(0, resourceSet.get());
        cmd->PushConstants(RHIShaderStage::Vertex, 0, sizeof(push), &push);
        cmd->BindVertexBuffer(vertexBuffer.get());
        cmd->BindIndexBuffer(indexBuffer.get(), RHIIndexType::U32);
        cmd->DrawIndexed(indexCount);

        device->EndFrame();
    }

    device->WaitIdle();   // GPU must finish before the resource unique_ptrs free
    glfwDestroyWindow(window);
    glfwTerminate();
    return 0;
}

} // namespace Diamond
